// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package external_bff

type CreateInventoryItemInput struct {
	Name              string  `json:"name"`
	IntroductionPrice float64 `json:"introductionPrice"`
}

type CreateTaxInput struct {
	Name    string  `json:"name"`
	TaxRate float64 `json:"taxRate"`
}

type Mutation struct {
}

type Query struct {
}
