mutation CreateTax($input: CreateTaxInput!) {
  createTax(fields: $input) {
    id
    name
    taxRate
    effectiveAt
    createdAt
    updatedAt
  }
}

query getAllTaxes {
  getAllTaxes {
    id
    name
    taxRate
    effectiveAt
    createdAt
    updatedAt
  }
}
