FROM golang:1.22.2-alpine3.19

ENV GO111MODULE=on
ENV IS_CI="true"

RUN apk add bash 
RUN apk add make
RUN apk add git
RUN apk add gcc
RUN apk add libc-dev
RUN apk add pkgconfig

WORKDIR /go/src/app

CMD [ "tail", "-f", "/dev/null" ]
