type Tax {
  id: UUID!
  name: String!
  taxRate: Float!
  effectiveAt: String!
  createdAt: String!
  updatedAt: String!
}

extend type Query {
  getAllTaxes: [Tax!]!
}

input CreateTaxInput {
  name: String!
  taxRate: Float!
}

extend type Mutation {
  createTax(fields: CreateTaxInput!): Tax!
  createTaxes(fields: [CreateTaxInput!]!): Boolean!
}
